# Generated by Django 4.1.6 on 2023-04-18 01:59

import datetime
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_signed', models.DateTimeField(default=datetime.datetime(2023, 4, 18, 2, 59, 39, 169080))),
                ('unique_id', models.UUIDField(default=uuid.uuid4)),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('course_code', models.CharField(blank=True, max_length=20, null=True)),
                ('date_created', models.DateTimeField(default=datetime.datetime(2023, 4, 18, 2, 59, 39, 168080))),
                ('unique_id', models.UUIDField(default=uuid.uuid4)),
            ],
        ),
        migrations.CreateModel(
            name='Guardians',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('unique_id', models.UUIDField(default=uuid.uuid4)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Institutions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('unique_id', models.UUIDField(default=uuid.uuid4)),
                ('date_created', models.DateTimeField(default=datetime.datetime(2023, 4, 18, 2, 59, 39, 169080))),
                ('Type', models.CharField(choices=[('Primary', 'primary'), ('Secondary', 'secondary'), ('Tetiary', 'tetiary')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=200)),
                ('unique_id', models.UUIDField(default=uuid.uuid4)),
                ('attendance', models.ManyToManyField(to='MarkMeApp.attendance')),
                ('courses', models.ManyToManyField(to='MarkMeApp.courses')),
                ('institutions', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='MarkMeApp.institutions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Instructors',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=200)),
                ('unique_id', models.UUIDField(default=uuid.uuid4)),
                ('attendance', models.ManyToManyField(to='MarkMeApp.attendance')),
                ('courses', models.ManyToManyField(to='MarkMeApp.courses')),
                ('institutions', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='MarkMeApp.institutions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='attendance',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarkMeApp.courses'),
        ),
    ]
