# Generated by Django 4.1.6 on 2023-04-18 02:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarkMeApp', '0002_rename_course_attendance_courses_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructors',
            name='attendance',
        ),
        migrations.RemoveField(
            model_name='students',
            name='attendance',
        ),
        migrations.AlterField(
            model_name='courses',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 18, 3, 5, 5, 927500)),
        ),
        migrations.AlterField(
            model_name='institutions',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 18, 3, 5, 5, 928500)),
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
