# Generated by Django 4.1.6 on 2023-04-18 02:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MarkMeApp', '0003_remove_instructors_attendance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_signed', models.DateTimeField(default=datetime.datetime(2023, 4, 18, 3, 10, 28, 341234))),
            ],
        ),
        migrations.RemoveField(
            model_name='courses',
            name='unique_id',
        ),
        migrations.RemoveField(
            model_name='institutions',
            name='unique_id',
        ),
        migrations.RemoveField(
            model_name='instructors',
            name='unique_id',
        ),
        migrations.RemoveField(
            model_name='students',
            name='unique_id',
        ),
        migrations.AlterField(
            model_name='courses',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 18, 3, 10, 28, 340235)),
        ),
        migrations.AlterField(
            model_name='institutions',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 18, 3, 10, 28, 340235)),
        ),
        migrations.DeleteModel(
            name='Guardians',
        ),
        migrations.AddField(
            model_name='attendance',
            name='courses',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarkMeApp.courses'),
        ),
        migrations.AddField(
            model_name='instructors',
            name='attendance',
            field=models.ManyToManyField(to='MarkMeApp.attendance'),
        ),
        migrations.AddField(
            model_name='students',
            name='attendance',
            field=models.ManyToManyField(to='MarkMeApp.attendance'),
        ),
    ]
