# Generated by Django 4.1.6 on 2023-04-18 02:12

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('MarkMeApp', '0004_attendance_remove_courses_unique_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='attendance',
        ),
        migrations.RemoveField(
            model_name='students',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='students',
            name='institutions',
        ),
        migrations.RemoveField(
            model_name='students',
            name='user_ptr',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='courses',
            new_name='course',
        ),
        migrations.AddField(
            model_name='attendance',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='courses',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='institutions',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date_signed',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 18, 3, 12, 16, 218722)),
        ),
        migrations.AlterField(
            model_name='courses',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 18, 3, 12, 16, 119726)),
        ),
        migrations.AlterField(
            model_name='institutions',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 18, 3, 12, 16, 218722)),
        ),
        migrations.DeleteModel(
            name='Instructors',
        ),
        migrations.DeleteModel(
            name='Students',
        ),
    ]
