# Generated by Django 4.1.8 on 2023-04-21 01:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarkMeApp', '0007_attendance_date_signed_courses_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructors',
            name='attendance_id',
            field=models.CharField(default='Y6bVBg', max_length=10),
        ),
        migrations.AddField(
            model_name='students',
            name='attendance_id',
            field=models.CharField(default='R-xgJg', max_length=10),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date_signed',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 21, 2, 9, 37, 448826)),
        ),
        migrations.AlterField(
            model_name='courses',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 21, 2, 9, 37, 447844)),
        ),
        migrations.AlterField(
            model_name='institutions',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 21, 2, 9, 37, 448826)),
        ),
    ]
