<<<<<<< HEAD
# Generated by Django 4.1.8 on 2023-04-21 00:18
=======
# Generated by Django 4.1.7 on 2023-04-20 21:05
>>>>>>> d1e04862305606e0f40dd5b291c252f76134c1f5

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarkMeApp', '0009_alter_attendance_date_signed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date_signed',
<<<<<<< HEAD
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 21, 1, 18, 34, 20697)),
=======
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 20, 22, 5, 54, 31427)),
>>>>>>> d1e04862305606e0f40dd5b291c252f76134c1f5
        ),
        migrations.AlterField(
            model_name='courses',
            name='date_created',
<<<<<<< HEAD
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 21, 1, 18, 34, 19697)),
=======
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 20, 22, 5, 54, 29427)),
>>>>>>> d1e04862305606e0f40dd5b291c252f76134c1f5
        ),
        migrations.AlterField(
            model_name='institutions',
            name='date_created',
<<<<<<< HEAD
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 21, 1, 18, 34, 20697)),
=======
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 20, 22, 5, 54, 31427)),
>>>>>>> d1e04862305606e0f40dd5b291c252f76134c1f5
        ),
    ]
