# Generated by Django 4.1.8 on 2023-04-21 11:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarkMeApp', '0013_attendance_academic_session_courses_academic_session_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='academic_session',
            field=models.CharField(default=datetime.datetime(2023, 4, 21, 12, 56, 38, 958245), max_length=20),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date_signed',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 21, 12, 56, 38, 958245)),
        ),
        migrations.AlterField(
            model_name='courses',
            name='academic_session',
            field=models.CharField(default=datetime.datetime(2023, 4, 21, 12, 56, 38, 957241), max_length=20),
        ),
        migrations.AlterField(
            model_name='courses',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 21, 12, 56, 38, 957241)),
        ),
        migrations.AlterField(
            model_name='institutions',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 21, 12, 56, 38, 957241)),
        ),
        migrations.AlterField(
            model_name='instructors',
            name='attendance_id',
            field=models.CharField(default='V8KObw', max_length=10),
        ),
        migrations.AlterField(
            model_name='students',
            name='attendance_id',
            field=models.CharField(default='0Wq5FA', max_length=10),
        ),
    ]
