# Generated by Django 4.1.8 on 2023-04-23 12:57

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('MarkMeApp', '0021_alter_attendance_date_signed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date_signed',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 23, 13, 57, 56, 995566)),
        ),
        migrations.AlterField(
            model_name='courses',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 23, 13, 57, 56, 994567)),
        ),
        migrations.AlterField(
            model_name='courses',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('c1985151-6429-43ec-9452-f230665f2956')),
        ),
        migrations.AlterField(
            model_name='institutions',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 23, 13, 57, 56, 995566)),
        ),
        migrations.AlterField(
            model_name='instructors',
            name='attendance_id',
            field=models.CharField(default='5NB6JQ', max_length=10),
        ),
        migrations.AlterField(
            model_name='students',
            name='attendance_id',
            field=models.CharField(default='8aPcqQ', max_length=50),
        ),
    ]
