# Generated by Django 4.1.8 on 2023-04-23 13:02

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('MarkMeApp', '0022_alter_attendance_date_signed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date_signed',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 23, 14, 2, 45, 214027)),
        ),
        migrations.AlterField(
            model_name='courses',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 23, 14, 2, 45, 213027)),
        ),
        migrations.AlterField(
            model_name='courses',
            name='unique_id',
            field=models.CharField(default=uuid.UUID('388ea946-f775-494e-94f5-8343b4645c19'), max_length=300),
        ),
        migrations.AlterField(
            model_name='institutions',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 23, 14, 2, 45, 213027)),
        ),
        migrations.AlterField(
            model_name='instructors',
            name='attendance_id',
            field=models.CharField(default='oSEt3A', max_length=10),
        ),
        migrations.AlterField(
            model_name='students',
            name='attendance_id',
            field=models.CharField(default='Xchy2w', max_length=50),
        ),
    ]
