# Generated by Django 4.1.8 on 2023-04-23 13:05

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('MarkMeApp', '0023_alter_attendance_date_signed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date_signed',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 23, 14, 5, 22, 22515)),
        ),
        migrations.AlterField(
            model_name='courses',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 23, 14, 5, 22, 21514)),
        ),
        migrations.AlterField(
            model_name='courses',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('63d51a6d-5556-4387-a02e-ce9d0b5806f9')),
        ),
        migrations.AlterField(
            model_name='institutions',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 23, 14, 5, 22, 22515)),
        ),
        migrations.AlterField(
            model_name='instructors',
            name='attendance_id',
            field=models.CharField(default='ydo8wQ', max_length=10),
        ),
        migrations.AlterField(
            model_name='students',
            name='attendance_id',
            field=models.CharField(default='6un2jQ', max_length=50),
        ),
    ]
