# Generated by Django 4.1.8 on 2023-04-23 13:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarkMeApp', '0025_alter_attendance_date_signed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='unique_id',
        ),
        migrations.AddField(
            model_name='courses',
            name='course_id',
            field=models.CharField(default='IdDdN2LaCqQ', max_length=50),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date_signed',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 23, 14, 16, 12, 199920)),
        ),
        migrations.AlterField(
            model_name='courses',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 23, 14, 16, 12, 198920)),
        ),
        migrations.AlterField(
            model_name='institutions',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 23, 14, 16, 12, 198920)),
        ),
        migrations.AlterField(
            model_name='instructors',
            name='attendance_id',
            field=models.CharField(default='MfYuMg', max_length=10),
        ),
        migrations.AlterField(
            model_name='students',
            name='attendance_id',
            field=models.CharField(default='MP6fOA', max_length=50),
        ),
    ]
