# Generated by Django 4.1.8 on 2023-04-23 13:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarkMeApp', '0026_remove_courses_unique_id_courses_course_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date_signed',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 23, 14, 16, 20, 946418)),
        ),
        migrations.AlterField(
            model_name='courses',
            name='course_id',
            field=models.CharField(default='a7NFil2Fw6A', max_length=50),
        ),
        migrations.AlterField(
            model_name='courses',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 23, 14, 16, 20, 945421)),
        ),
        migrations.AlterField(
            model_name='institutions',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 23, 14, 16, 20, 945421)),
        ),
        migrations.AlterField(
            model_name='instructors',
            name='attendance_id',
            field=models.CharField(default='_5C2Cw', max_length=10),
        ),
        migrations.AlterField(
            model_name='students',
            name='attendance_id',
            field=models.CharField(default='TVLLig', max_length=50),
        ),
    ]
