# Generated by Django 4.1.8 on 2023-04-25 10:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarkMeApp', '0027_alter_attendance_date_signed_alter_courses_course_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='instructor',
            field=models.CharField(default='Anonymous', max_length=200),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.CharField(default='Anonymous', max_length=200),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date_signed',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 25, 11, 28, 21, 439232)),
        ),
        migrations.AlterField(
            model_name='courses',
            name='course_id',
            field=models.CharField(default='sJBokIGlRqM', max_length=50),
        ),
        migrations.AlterField(
            model_name='courses',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 25, 11, 28, 21, 438232)),
        ),
        migrations.AlterField(
            model_name='institutions',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 25, 11, 28, 21, 439232)),
        ),
        migrations.AlterField(
            model_name='instructors',
            name='attendance_id',
            field=models.CharField(default='sFnfrQ', max_length=10),
        ),
        migrations.AlterField(
            model_name='students',
            name='attendance_id',
            field=models.CharField(default='2nU-5w', max_length=50),
        ),
    ]
