# Generated by Django 4.1.8 on 2023-04-25 14:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarkMeApp', '0029_alter_attendance_date_signed_alter_courses_course_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date_signed',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 25, 15, 44, 41, 28344)),
        ),
        migrations.AlterField(
            model_name='courses',
            name='course_id',
            field=models.CharField(default='jlYb2lpGycY', max_length=50),
        ),
        migrations.AlterField(
            model_name='courses',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 25, 15, 44, 41, 27343)),
        ),
        migrations.AlterField(
            model_name='institutions',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 25, 15, 44, 41, 28344)),
        ),
        migrations.AlterField(
            model_name='instructors',
            name='attendance_id',
            field=models.CharField(default='4z6Ydw', max_length=10),
        ),
        migrations.AlterField(
            model_name='students',
            name='attendance_id',
            field=models.CharField(default='ctcaJA', max_length=50),
        ),
    ]
