# Generated by Django 4.1.8 on 2023-04-26 22:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarkMeApp', '0030_alter_attendance_date_signed_alter_courses_course_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='course_name',
            field=models.CharField(default='Course name', max_length=200),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date_signed',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 26, 23, 25, 23, 997060)),
        ),
        migrations.AlterField(
            model_name='courses',
            name='course_id',
            field=models.CharField(default='XdDMONUXWjg', max_length=50),
        ),
        migrations.AlterField(
            model_name='courses',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 26, 23, 25, 23, 994055)),
        ),
        migrations.AlterField(
            model_name='institutions',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 26, 23, 25, 23, 995055)),
        ),
        migrations.AlterField(
            model_name='instructors',
            name='attendance_id',
            field=models.CharField(default='9-wNlA', max_length=10),
        ),
        migrations.AlterField(
            model_name='students',
            name='attendance_id',
            field=models.CharField(default='hAfItA', max_length=50),
        ),
    ]
